### ISSUE TITLE
Question about functionality

### ISSUE THREAD

**Issue by Ved-un** [Helltar/plainotepad#1]
Hello.
Thank you for your work !
Simple and fast editor.

I wanted to ask - are you planning to add the transfer of long lines and the files opening dialog box?

If it doesn't complicate the code of course...

**Comment by Helltar** [comment]
Hi, thank.

I'll add the file opening dialog, about lines break I can't say yet, it's not supported in the component that is used, but I'll look (I think I saw a non-official version/fork).

**Comment by Ved-un** [comment]
Thank you for your reply.
You can do without transferring long lines, but "open file" wouldn't hurt.

**Comment by Ved-un** [comment]
And I also wanted to ask - how to build your program from fresh sources?
Because I have a binary from the release where there are no new features.

I need an instruction on how to build from source.
You can also add it to the project description.

EDIT:
Ahh... I see, I will have to install Lazarus for this program, and it weighs more than 1 gigabyte with dependencies ((
--  then maybe you yourself will update the binary?

**Comment by Helltar** [comment]
> then maybe you yourself will update the binary?

Yes, there will be a new version tomorrow or the day after tomorrow.

Upd: already

- [Plainotepad v0.2.0](https://github.com/Helltar/plainotepad/releases/tag/0.2.0)

**Comment by Helltar** [comment]
- [Plainotepad v0.2.0](https://github.com/Helltar/plainotepad/releases/tag/0.2.0)
