### ISSUE TITLE
The previous window size is not saved

### ISSUE THREAD

**Issue by Ved-un** [Helltar/plainotepad#2]
Hello.
Now I tried the new version and had two problems:
- When you start the editor again does not save the previous size of the window, and if you restart it - the window with each start decreases in size.

- And also a problem with the size of the font - it is a little larger in size than it is actually set.

**Comment by Helltar** [comment]
Hi, this setting does not affect the menu font (file, edit, view), as it is a system menu, the size corresponds to the system settings.

Do you use this font in the editor? https://archlinux.org/packages/community/any/ttc-iosevka-ss18/

**Comment by Ved-un** [comment]
> Do you use this font in the editor? https://archlinux.org/packages/community/any/ttc-iosevka-ss18/

Yes

I know that the setting has no effect on the menu font - I showed to compare the sizes of the fonts, because the system is the same installed - Iosevka SS18 with a size of 10

**Comment by Ved-un** [comment]
I can try with a different font - Open Sans, for example...

-------------------------
P.S.
Everything is fine with the Open Sans - the font size is the same.

So something is wrong with the font Iosevka, although it's the first time - in other programs, I have no such thing

**Comment by Ved-un** [comment]
... Also now noticed that the running **plainotepad** is not displayed in the panel - probably because of this and the dimensions are not saved, since the panel does not see the window ...

My panel shows the CLASS of the window

Now I checked it with xprop - it shows TITLE instead of CLASS

![flameshot_335_3](https://user-images.githubusercontent.com/48730277/205133680-f63ca582-0162-4a6e-9c7e-948ef85adb9e.png)

**Comment by Ved-un** [comment]
Downloaded the previous **Plainotepad v0.2.0** binary 

Everything is fine here

![flameshot_335_5](https://user-images.githubusercontent.com/48730277/205136629-94abb380-ef04-4974-ab86-2835e8fafb4f.png)

And the window size is remembered
There's nothing wrong with the font in this version either, so I'll leave this version for now

**Comment by Helltar** [comment]
8eb8855b8053b14118b8d2ee65b78204e716259e I fixed the problem with the font, it's "line height". Now I will look at the rest.

**Comment by Ved-un** [comment]
Thanks, but I can't test it because I have to compile it  (
I'm having trouble loading github today too

**Comment by Helltar** [comment]
It seems to have fixed the problem with "CLASS". I'm now fine with window sizes (KDE). Please check if you can:
- [plainotepad.tar.gz](https://github.com/Helltar/plainotepad/files/10135497/plainotepad.tar.gz)

**Comment by Ved-un** [comment]
Tested on **Arch** with the wm **BSPWM**
Everything seems to be working fine, thank you very much!
