### ISSUE TITLE
No syntax coloring for C#

### ISSUE THREAD

**Issue by Baltasarq** [Helltar/plainotepad#5]
## Intro

When a *.cs files is opened, the file is shown in the plain, default colors.

## Expected behaviour

When a *.cs is opened, or when the current file is saved or saved as, the current file should be recolored with the appropriate syntax color.

## Discussion

I don't know how many syntax color templates are available, or which are accepted by the current engine. In any case, if a C# template is missing, it can be easily created from the C++ one. I volunteer to do the job if needed, though I've found the template here (following the URL's you left in GitHub):

https://sourceforge.net/projects/cudatext/files/addons/lexers/lexer.C%23.zip/download

**Comment by Helltar** [comment]
Hello, yes, you can take the C#.lcf file from this archive and move it to:

```bash
mv C#.lcf ~/.config/plainotepad/synt-analyzers/
```

Then, edit the highlight colors in the theme editor within the plainotepad settings, it should work.

I'll add this C# syntax highlighting to the release this weekend.
